[features]
seeds = false
skip-lint = false
[programs.localnet]
group8 = "25XSG7yVjFTQhcantbjHU4Auw8gmtDk1CdqPqjGwMLTm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/devbox/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
