[features]
seeds = false
skip-lint = false
[programs.localnet]
group8 = "22ekZxqp1gGqWVmbKdJegrzvJR4E8sLsQRcVZGjoMwvC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/Owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
